# Generated by Django 2.1.7 on 2020-11-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Followup',
            fields=[
                ('followup_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_followup', models.DateField()),
                ('response', models.CharField(blank=True, max_length=100)),
                ('medium_used', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('lead_id', models.AutoField(primary_key=True, serialize=False)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=12)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('current_stage', models.CharField(blank=True, max_length=100)),
                ('followup_id', models.ManyToManyField(to='app.Followup')),
            ],
        ),
    ]
